best application is I force myself to use english everywhere  
when I use chatgpt, I type in english and read english expplination  
I don't install Chinese spell in my computer...  
read english material if I can, never translate it back to Chinese...  
